[theme]
primaryColor = "#E30613"
backgroundColor = "#FAFBFC"
secondaryBackgroundColor = "#F2F4F7"
textColor = "#0B1C2D"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
