[theme]
primaryColor = "#E30613"                 # PSV red
backgroundColor = "#FFFFFF"              # white
secondaryBackgroundColor = "#F2F2F2"      # light grey
textColor = "#0B1C2D"                     # dark navy
font = "sans serif"